version: '3.5'
services:
  book-postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=book
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  book-backend:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_HOST=book-postgres
      - DB_PORT=5432
      - DB_DATABASE=book
    depends_on:
      - book-postgres