DROP TABLE IF EXISTS book;
CREATE SEQUENCE book_id START 1;
CREATE TABLE book (
    BOOK_ID serial PRIMARY KEY,
    TITLE VARCHAR NOT NULL,
    DESCRIPTION VARCHAR NOT NULL,
    PRICE INT NOT NULL,
    RATING INT NOT NULL,
    DISCOUNT INT,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL
);
